### ISSUE TITLE
Замечания по lw4

### ISSUE THREAD

**Issue by ivklgn** [mrjayse/lw4-2019#1]
- структура репозитория запутанная, разбейте по папкам подпроекты
- нарушено форматирование
- имя класса goods неверное, лучше product
- section для продуктов применен неверно
- ссылка перехода на товар работает только по клику на картинку
- no-deco-link - непонятный css id, лучше использовать класс и норм имя
- должен быть класс отдельный:
```css
header div {
    display: inline-block;
    margin-top: 20px;
    margin-bottom: 20px;
}
```
- лучше стили вешать на классы а не на элементы (перепроверить весь код)
```css
nav li {
    margin-bottom: 10px;
    list-style-type: none;
}
```
